"use client";

import { useState } from "react";
import { parseReceiptText } from "@/lib/ocr";
import { createFuelLog } from "@/app/(protected)/actions";
import { buttonClass, fieldClass } from "@/components/operations";

export function ReceiptOcr({ vehicles }: { vehicles: { id: string; name: string; registrationNumber: string; odometer: number }[] }) {
  const [progress,setProgress]=useState(0),[raw,setRaw]=useState(""),[parsed,setParsed]=useState<ReturnType<typeof parseReceiptText>|null>(null),[busy,setBusy]=useState(false);
  async function extract(file?: File){if(!file)return;setBusy(true);setRaw("");const {createWorker}=await import("tesseract.js");const worker=await createWorker("eng",undefined,{logger:m=>m.status==="recognizing text"&&setProgress(Math.round((m.progress||0)*100))});const result=await worker.recognize(file);await worker.terminate();setRaw(result.data.text);setParsed(parseReceiptText(result.data.text));setBusy(false);}
  const matched=vehicles.find(v=>parsed?.registrationNumber&&v.registrationNumber.replaceAll("-","").includes(parsed.registrationNumber.replaceAll(/[ -]/g,"")));
  return <form action={createFuelLog} className="grid gap-3"><label className="grid gap-1 text-xs font-bold">Receipt image<input name="receipt" type="file" accept="image/png,image/jpeg,application/pdf" required className={fieldClass} onChange={e=>extract(e.target.files?.[0])}/></label>{busy&&<div className="rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:`${progress}%`}}/></div>}{raw&&<details open className="rounded-2xl bg-muted p-3"><summary className="cursor-pointer text-sm font-bold">Review OCR text</summary><pre className="mt-2 max-h-32 overflow-auto whitespace-pre-wrap text-xs">{raw}</pre></details>}<input type="hidden" name="rawOcrText" value={raw}/><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Vehicle<select name="vehicleId" defaultValue={matched?.id} required className={fieldClass}>{vehicles.map(v=><option key={v.id} value={v.id}>{v.name} · {v.registrationNumber}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Date<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Litres<input key={`litres-${parsed?.litres}`} name="litres" type="number" step=".01" defaultValue={parsed?.litres} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Total cost<input key={`amount-${parsed?.amount}`} name="cost" type="number" step=".01" defaultValue={parsed?.amount} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Odometer<input name="odometer" type="number" defaultValue={matched?.odometer||vehicles[0]?.odometer} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Fuel station<input key={`vendor-${parsed?.vendor}`} name="fuelStation" defaultValue={parsed?.vendor} className={fieldClass}/></label></div><p className="text-xs text-muted-foreground">OCR never saves automatically. Review and correct every field before accepting.</p><button disabled={!raw||busy} className={buttonClass}>Accept reviewed values & save</button></form>;
}
