import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { db } from "@/lib/db";
import { fleetUtilization, fuelEfficiency, onTimePerformance, operationalCost } from "@/lib/analytics";

const palette = { loam: "#2C2C24", moss: "#5D7052", clay: "#C18C5D", mist: "#F3F4F1", timber: "#DED8CF", grass: "#78786C", paper: "#FDFCF8" };

const styles = StyleSheet.create({
  page: { padding: 40, paddingBottom: 64, fontSize: 9, color: palette.loam, backgroundColor: palette.paper, fontFamily: "Helvetica" },
  brandRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", borderBottomWidth: 2, borderBottomColor: palette.moss, paddingBottom: 10, marginBottom: 16 },
  brand: { fontSize: 16, fontFamily: "Helvetica-Bold", color: palette.moss },
  title: { fontSize: 13, fontFamily: "Helvetica-Bold", marginTop: 2 },
  meta: { fontSize: 8, color: palette.grass, textAlign: "right" },
  kpiRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  kpi: { flex: 1, backgroundColor: palette.mist, borderRadius: 10, padding: 10 },
  kpiLabel: { fontSize: 7, color: palette.grass, textTransform: "uppercase" },
  kpiValue: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 4, color: palette.moss },
  sectionTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 6, marginTop: 10, color: palette.loam },
  headRow: { flexDirection: "row", backgroundColor: palette.mist, borderRadius: 6, paddingVertical: 6, paddingHorizontal: 8, fontFamily: "Helvetica-Bold", fontSize: 8 },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: palette.timber, paddingVertical: 6, paddingHorizontal: 8 },
  totalRow: { flexDirection: "row", paddingVertical: 8, paddingHorizontal: 8, fontFamily: "Helvetica-Bold", backgroundColor: palette.mist, borderRadius: 6, marginTop: 4 },
  footer: { position: "absolute", bottom: 28, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", fontSize: 7, color: palette.grass, borderTopWidth: 0.5, borderTopColor: palette.timber, paddingTop: 8 },
  badge: { color: palette.clay, fontFamily: "Helvetica-Bold" },
});

const inr = (n: number | null | undefined) => `Rs ${Math.round(n || 0).toLocaleString("en-IN")}`;
const dmy = (d: Date | null | undefined) => (d ? d.toLocaleDateString("en-IN") : "—");

function Frame({ title, generatedBy, children }: { title: string; generatedBy: string; children: React.ReactNode }) {
  return (
    <Document title={`TransitOps — ${title}`} author="TransitOps">
      <Page size="A4" style={styles.page}>
        <View style={styles.brandRow} fixed>
          <View>
            <Text style={styles.brand}>TransitOps</Text>
            <Text style={styles.title}>{title}</Text>
          </View>
          <View>
            <Text style={styles.meta}>Generated {new Date().toLocaleString("en-IN")}</Text>
            <Text style={styles.meta}>Generated by {generatedBy}</Text>
          </View>
        </View>
        {children}
        <View style={styles.footer} fixed>
          <Text>TransitOps — Smart Transport Operations Platform</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}

function Table({ widths, head, rows, total }: { widths: number[]; head: string[]; rows: (string | number)[][]; total?: (string | number)[] }) {
  const cell = (v: string | number, i: number, bold = false) => (
    <Text key={i} style={{ flex: widths[i], paddingRight: 4, ...(bold ? { fontFamily: "Helvetica-Bold" } : {}) }}>{String(v ?? "—")}</Text>
  );
  return (
    <View>
      <View style={styles.headRow}>{head.map((h, i) => cell(h, i, true))}</View>
      {rows.map((r, ri) => (
        <View key={ri} style={styles.row} wrap={false}>{r.map((v, i) => cell(v, i))}</View>
      ))}
      {total && <View style={styles.totalRow}>{total.map((v, i) => cell(v, i, true))}</View>}
    </View>
  );
}

export async function buildReportPdf(report: string, generatedBy: string, id?: string): Promise<{ buffer: Buffer; filename: string } | null> {
  if (report === "fleet" || report === "fleet-summary") {
    const [vehicles, trips, fuel, maintenance, expenses] = await Promise.all([
      db.vehicle.findMany({ orderBy: { name: "asc" } }),
      db.trip.findMany(),
      db.fuelLog.findMany(),
      db.maintenanceLog.findMany(),
      db.expense.findMany({ where: { status: "APPROVED" } }),
    ]);
    const completed = trips.filter((t) => t.status === "COMPLETED");
    const cost = operationalCost(fuel.reduce((s, f) => s + f.cost, 0), maintenance.reduce((s, m) => s + (m.actualCost || 0), 0), expenses.reduce((s, e) => s + e.amount, 0));
    const buffer = await renderToBuffer(
      <Frame title="Fleet Summary Report" generatedBy={generatedBy}>
        <View style={styles.kpiRow}>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Fleet utilization</Text><Text style={styles.kpiValue}>{fleetUtilization(vehicles)}%</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>On-time performance</Text><Text style={styles.kpiValue}>{onTimePerformance(trips)}%</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Operational cost</Text><Text style={styles.kpiValue}>{inr(cost)}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Fuel efficiency</Text><Text style={styles.kpiValue}>{fuelEfficiency(completed.reduce((s, t) => s + t.plannedDistance, 0), fuel.reduce((s, f) => s + f.litres, 0))} km/L</Text></View>
        </View>
        <Text style={styles.sectionTitle}>Vehicle registry ({vehicles.length})</Text>
        <Table
          widths={[1.2, 1.4, 0.9, 0.8, 1, 1, 1]}
          head={["Vehicle", "Registration", "Type", "Status", "Odometer", "Insurance", "Fitness"]}
          rows={vehicles.map((v) => [v.name, v.registrationNumber, v.type, v.status, `${v.odometer.toLocaleString("en-IN")} km`, dmy(v.insuranceExpiry), dmy(v.fitnessExpiry)])}
        />
        <Text style={styles.sectionTitle}>Trips ({trips.length})</Text>
        <Table
          widths={[1, 1.6, 0.9, 1, 1]}
          head={["Trip", "Route", "Status", "Revenue", "Est. margin"]}
          rows={trips.map((t) => [t.tripNumber, `${t.source} - ${t.destination}`, t.status, inr(t.expectedRevenue), inr(t.estimatedMargin)])}
          total={["Total", "", "", inr(trips.reduce((s, t) => s + t.expectedRevenue, 0)), inr(trips.reduce((s, t) => s + t.estimatedMargin, 0))]}
        />
      </Frame>,
    );
    return { buffer, filename: "transitops-fleet-summary.pdf" };
  }

  if (report === "vehicle-detail") {
    const vehicle = id
      ? await db.vehicle.findUnique({ where: { id }, include: { trips: true, maintenanceLogs: true, fuelLogs: true, expenses: true } })
      : await db.vehicle.findFirst({ include: { trips: true, maintenanceLogs: true, fuelLogs: true, expenses: true }, orderBy: { name: "asc" } });
    if (!vehicle) return null;
    const cost = operationalCost(vehicle.fuelLogs.reduce((s, f) => s + f.cost, 0), vehicle.maintenanceLogs.reduce((s, m) => s + (m.actualCost || 0), 0), vehicle.expenses.filter((e) => e.status === "APPROVED").reduce((s, e) => s + e.amount, 0));
    const buffer = await renderToBuffer(
      <Frame title={`Vehicle Detail — ${vehicle.name}`} generatedBy={generatedBy}>
        <View style={styles.kpiRow}>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Registration</Text><Text style={styles.kpiValue}>{vehicle.registrationNumber}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Status</Text><Text style={styles.kpiValue}>{vehicle.status}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Odometer</Text><Text style={styles.kpiValue}>{vehicle.odometer.toLocaleString("en-IN")} km</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Operational cost</Text><Text style={styles.kpiValue}>{inr(cost)}</Text></View>
        </View>
        <Text style={styles.sectionTitle}>Document validity</Text>
        <Table widths={[1.5, 1]} head={["Document", "Expires"]}
          rows={[["Insurance", dmy(vehicle.insuranceExpiry)], ["Registration", dmy(vehicle.registrationExpiry)], ["Pollution certificate", dmy(vehicle.pollutionExpiry)], ["Fitness certificate", dmy(vehicle.fitnessExpiry)], ["Permit", dmy(vehicle.permitExpiry)]]} />
        <Text style={styles.sectionTitle}>Trip history ({vehicle.trips.length})</Text>
        <Table widths={[1, 1.6, 0.9, 1]} head={["Trip", "Route", "Status", "Revenue"]}
          rows={vehicle.trips.map((t) => [t.tripNumber, `${t.source} - ${t.destination}`, t.status, inr(t.expectedRevenue)])} />
        <Text style={styles.sectionTitle}>Maintenance history ({vehicle.maintenanceLogs.length})</Text>
        <Table widths={[1.4, 1, 0.9, 1]} head={["Service", "Scheduled", "Status", "Cost"]}
          rows={vehicle.maintenanceLogs.map((m) => [m.serviceType, dmy(m.scheduledDate), m.status, inr(m.actualCost ?? m.estimatedCost)])} />
      </Frame>,
    );
    return { buffer, filename: `transitops-vehicle-${vehicle.name.toLowerCase()}.pdf` };
  }

  if (report === "trip-completion") {
    const trip = id
      ? await db.trip.findUnique({ where: { id }, include: { vehicle: true, driver: true, events: { orderBy: { createdAt: "asc" } } } })
      : await db.trip.findFirst({ where: { status: "COMPLETED" }, include: { vehicle: true, driver: true, events: { orderBy: { createdAt: "asc" } } }, orderBy: { actualCompletion: "desc" } });
    if (!trip) return null;
    const distance = trip.finalOdometer && trip.startingOdometer ? trip.finalOdometer - trip.startingOdometer : trip.plannedDistance;
    const buffer = await renderToBuffer(
      <Frame title={`Trip Completion — ${trip.tripNumber}`} generatedBy={generatedBy}>
        <View style={styles.kpiRow}>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Route</Text><Text style={styles.kpiValue}>{trip.source} - {trip.destination}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Status</Text><Text style={styles.kpiValue}>{trip.status}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Distance</Text><Text style={styles.kpiValue}>{distance} km</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Revenue</Text><Text style={styles.kpiValue}>{inr(trip.expectedRevenue)}</Text></View>
        </View>
        <Text style={styles.sectionTitle}>Assignment &amp; execution</Text>
        <Table widths={[1.5, 1.5]} head={["Field", "Value"]}
          rows={[["Vehicle", trip.vehicle?.name ?? "—"], ["Driver", trip.driver?.name ?? "—"], ["Cargo", `${trip.cargoDescription} (${trip.cargoWeight} kg)`], ["Planned window", `${dmy(trip.plannedStart)} - ${dmy(trip.plannedCompletion)}`], ["Actual start", trip.actualStart ? trip.actualStart.toLocaleString("en-IN") : "—"], ["Actual completion", trip.actualCompletion ? trip.actualCompletion.toLocaleString("en-IN") : "—"], ["Starting odometer", `${trip.startingOdometer ?? "—"} km`], ["Final odometer", `${trip.finalOdometer ?? "—"} km`], ["Fuel consumed", trip.actualFuelConsumed ? `${trip.actualFuelConsumed} L (${inr(trip.actualFuelCost)})` : "—"]]} />
        <Text style={styles.sectionTitle}>Economics</Text>
        <Table widths={[1.5, 1]} head={["Line", "Amount"]}
          rows={[["Expected revenue", inr(trip.expectedRevenue)], ["Estimated fuel", inr(trip.estimatedFuelCost)], ["Estimated tolls", inr(trip.estimatedTollCost)], ["Maintenance reserve", inr(trip.estimatedMaintenanceReserve)]]}
          total={["Estimated margin", inr(trip.estimatedMargin)]} />
        <Text style={styles.sectionTitle}>Event timeline</Text>
        <Table widths={[1, 2, 1]} head={["Event", "Detail", "At"]}
          rows={trip.events.map((e) => [e.type, e.message, e.createdAt.toLocaleString("en-IN")])} />
      </Frame>,
    );
    return { buffer, filename: `transitops-${trip.tripNumber.toLowerCase()}.pdf` };
  }

  if (report === "expense-report") {
    const expenses = await db.expense.findMany({ include: { vehicle: true, trip: true }, orderBy: { date: "desc" } });
    const approved = expenses.filter((e) => e.status === "APPROVED");
    const byCategory = Object.entries(approved.reduce<Record<string, number>>((acc, e) => ({ ...acc, [e.category]: (acc[e.category] || 0) + e.amount }), {}));
    const buffer = await renderToBuffer(
      <Frame title="Expense Report" generatedBy={generatedBy}>
        <View style={styles.kpiRow}>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Submitted</Text><Text style={styles.kpiValue}>{expenses.length}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Approved</Text><Text style={styles.kpiValue}>{approved.length}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Pending</Text><Text style={styles.kpiValue}>{expenses.filter((e) => e.status === "PENDING").length}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Approved spend</Text><Text style={styles.kpiValue}>{inr(approved.reduce((s, e) => s + e.amount, 0))}</Text></View>
        </View>
        <Text style={styles.sectionTitle}>Approved spend by category</Text>
        <Table widths={[1.5, 1]} head={["Category", "Amount"]} rows={byCategory.map(([c, v]) => [c, inr(v)])}
          total={["Total", inr(approved.reduce((s, e) => s + e.amount, 0))]} />
        <Text style={styles.sectionTitle}>All expenses</Text>
        <Table widths={[0.9, 1, 1, 0.8, 1.6, 0.8]} head={["Date", "Vehicle", "Category", "Amount", "Description", "Status"]}
          rows={expenses.map((e) => [dmy(e.date), e.vehicle?.name ?? "—", e.category, inr(e.amount), e.description, e.status])} />
      </Frame>,
    );
    return { buffer, filename: "transitops-expense-report.pdf" };
  }

  if (report === "compliance-report") {
    const alerts = await db.complianceAlert.findMany({ orderBy: [{ status: "asc" }, { severity: "asc" }, { createdAt: "desc" }] });
    const open = alerts.filter((a) => a.status === "OPEN");
    const buffer = await renderToBuffer(
      <Frame title="Compliance Report" generatedBy={generatedBy}>
        <View style={styles.kpiRow}>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Open alerts</Text><Text style={styles.kpiValue}>{open.length}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Critical</Text><Text style={styles.kpiValue}>{open.filter((a) => a.severity === "CRITICAL").length}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Warnings</Text><Text style={styles.kpiValue}>{open.filter((a) => a.severity === "WARNING").length}</Text></View>
          <View style={styles.kpi}><Text style={styles.kpiLabel}>Resolved</Text><Text style={styles.kpiValue}>{alerts.length - open.length}</Text></View>
        </View>
        <Text style={styles.sectionTitle}>Alert register ({alerts.length})</Text>
        <Table widths={[0.8, 0.8, 2.4, 0.9, 0.8]} head={["Severity", "Entity", "Message", "Due", "Status"]}
          rows={alerts.map((a) => [a.severity, a.entityType, a.message, dmy(a.dueDate), a.status])} />
      </Frame>,
    );
    return { buffer, filename: "transitops-compliance-report.pdf" };
  }

  return null;
}
