import { db } from "@/lib/db";
import { requirePermission } from "@/lib/auth/current-user";
import { hasPermission } from "@/lib/auth/permissions";
import { recommendDispatch } from "@/lib/dispatch";
import { fallbackRoute, locations } from "@/lib/routes";
import { buttonClass, cardClass, fieldClass, PageHeader, StatCard, StatusBadge } from "@/components/operations";
import { cancelTrip, completeTrip, createTrip, dispatchTrip } from "../actions";

export const dynamic = "force-dynamic";

export default async function TripsPage({ searchParams }: { searchParams?: Promise<{ source?: string; destination?: string; cargo?: string; revenue?: string; message?: string; error?: string }> }) {
  const params = await searchParams;
  const user = await requirePermission("read:trips");
  const canManage = hasPermission(user, "manage:trips");
  const [trips, vehicles, drivers] = await Promise.all([db.trip.findMany({ include: { vehicle: true, driver: true }, orderBy: { createdAt: "desc" } }), db.vehicle.findMany({ orderBy: { name: "asc" } }), db.driver.findMany({ orderBy: { name: "asc" } })]);
  const source = params?.source || "Mumbai", destination = params?.destination || "Pune", cargo = Number(params?.cargo || 450), revenue = Number(params?.revenue || 36500);
  const route = fallbackRoute(source, destination), completion = new Date(Date.now() + 2 * 86_400_000);
  const recommendation = recommendDispatch({ cargoWeight: cargo, distanceKm: route.distanceKm, expectedRevenue: revenue, plannedCompletion: completion }, vehicles.map(v => ({ id: v.id, name: v.name, status: v.status, type: v.type, maxLoadCapacity: v.maxLoadCapacity, fuelEfficiency: v.type.includes("Truck") ? 6 : 12, documentsValid: [v.insuranceExpiry,v.registrationExpiry,v.pollutionExpiry,v.fitnessExpiry,v.permitExpiry].every(d=>d>=completion), maintenanceHealthy: v.status !== "IN_SHOP" })), drivers.map(d => ({ id:d.id,name:d.name,status:d.status,licenceCategory:d.licenceCategory,licenceExpiry:d.licenceExpiry,safetyScore:d.safetyScore })));
  const tomorrow = new Date(Date.now()+86_400_000).toISOString().slice(0,16), dayAfter = new Date(Date.now()+2*86_400_000).toISOString().slice(0,16);
  return <div><PageHeader eyebrow="Live operations" title="Trip Dispatcher" description="Validate capacity, compliance, schedules and profitability before resources move." />
    {(params?.message || params?.error) && <p role="status" className={`mb-4 rounded-2xl p-3 text-sm ${params.error ? "bg-red-100 text-red-800" : "bg-primary/10 text-primary"}`}>{params.message || params.error}</p>}
    <section className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active trips" value={trips.filter(t=>t.status==="DISPATCHED").length}/><StatCard label="Drafts" value={trips.filter(t=>t.status==="DRAFT").length}/><StatCard label="Completed" value={trips.filter(t=>t.status==="COMPLETED").length}/><StatCard label="Planned revenue" value={`₹${trips.reduce((s,t)=>s+t.expectedRevenue,0).toLocaleString("en-IN")}`}/></section>
    <div className="mb-6 grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
      {canManage && <form action={createTrip} className={cardClass}><h2 className="mb-4 text-xl font-semibold">Create trip</h2><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Source<select name="source" className={fieldClass}>{Object.keys(locations).map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Destination<select name="destination" defaultValue="Pune" className={fieldClass}>{Object.keys(locations).map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Vehicle<select name="vehicleId" defaultValue={recommendation.best?.vehicle.id} className={fieldClass}>{vehicles.filter(v=>v.status!=="RETIRED").map(v=><option key={v.id} value={v.id}>{v.name} · {v.status}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Driver<select name="driverId" defaultValue={recommendation.best?.driver.id} className={fieldClass}>{drivers.map(d=><option key={d.id} value={d.id}>{d.name} · {d.status}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Cargo weight (kg)<input name="cargoWeight" type="number" defaultValue={cargo} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Expected revenue (₹)<input name="expectedRevenue" type="number" defaultValue={revenue} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Planned start<input name="plannedStart" type="datetime-local" defaultValue={tomorrow} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold">Planned completion<input name="plannedCompletion" type="datetime-local" defaultValue={dayAfter} required className={fieldClass}/></label><label className="grid gap-1 text-xs font-bold sm:col-span-2">Cargo description<input name="cargoDescription" defaultValue="General cargo" required className={fieldClass}/></label><button className={`${buttonClass} sm:col-span-2`}>Save draft</button></div></form>}
      <section className={cardClass}><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Smart Dispatch Assistant</p><h2 className="mt-1 text-xl font-semibold">{recommendation.best ? `${recommendation.best.vehicle.name} + ${recommendation.best.driver.name}` : "No eligible pair"}</h2></div>{recommendation.best && <span className="grid h-16 w-16 place-items-center rounded-full bg-primary text-xl font-bold text-primary-foreground">{recommendation.best.score}</span>}</div>{recommendation.best && <><ul className="my-4 grid gap-2 text-sm">{recommendation.best.reasons.map(r=><li key={r}>✓ {r}</li>)}</ul><div className="grid grid-cols-3 gap-2 rounded-2xl bg-muted p-3 text-center text-xs"><div>Distance<strong className="block text-base">{route.distanceKm} km</strong></div><div>Break-even<strong className="block text-base">₹{recommendation.best.breakEvenRevenue.toLocaleString("en-IN")}</strong></div><div>Margin<strong className="block text-base text-primary">₹{recommendation.best.estimatedMargin.toLocaleString("en-IN")}</strong></div></div></>}<details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-primary">Rejected candidates ({recommendation.rejected.length})</summary><ul className="mt-2 space-y-1 text-xs text-muted-foreground">{recommendation.rejected.map(r=><li key={r}>{r}</li>)}</ul></details></section>
      <section className={`${cardClass} xl:col-span-2`}><div className="grid gap-4 md:grid-cols-[1fr_240px]"><div className="relative min-h-52 overflow-hidden rounded-[1.5rem] bg-[#e8eadf] dark:bg-[#182016]"><svg viewBox="0 0 500 210" className="h-full w-full" aria-label={`${source} to ${destination} demo route`}><defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="currentColor" opacity=".09"/></pattern></defs><rect width="500" height="210" fill="url(#grid)"/><path d="M55 165 C155 35 315 185 445 45" fill="none" stroke="#5D7052" strokeWidth="6" strokeLinecap="round" strokeDasharray="10 8"/><circle cx="55" cy="165" r="10" fill="#5D7052"/><circle cx="445" cy="45" r="10" fill="#C18C5D"/></svg><span className="absolute bottom-3 left-3 rounded-full bg-card/90 px-3 py-1 text-xs">Demo route estimate · offline safe</span></div><div><p className="text-xs uppercase text-muted-foreground">Route overview</p><h3 className="mt-2 text-2xl font-semibold">{source} → {destination}</h3><dl className="mt-5 grid gap-3 text-sm"><div><dt className="text-muted-foreground">Distance</dt><dd className="font-bold">{route.distanceKm} km</dd></div><div><dt className="text-muted-foreground">Duration</dt><dd className="font-bold">{Math.floor(route.durationMinutes/60)}h {route.durationMinutes%60}m</dd></div><div><dt className="text-muted-foreground">Routing</dt><dd className="font-bold text-primary">Deterministic fallback</dd></div></dl></div></div></section>
    </div>
    <div className={`${cardClass} overflow-x-auto p-0`}><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b bg-muted/60 text-xs uppercase text-muted-foreground"><tr>{["Trip","Route","Schedule","Assignment","Cargo","Economics","Status","Actions"].map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{trips.map(t=><tr key={t.id} className="border-b align-top last:border-0"><td className="px-5 py-4 font-bold">{t.tripNumber}</td><td className="px-5 py-4">{t.source} → {t.destination}<span className="block text-xs text-muted-foreground">{t.plannedDistance} km</span></td><td className="px-5 py-4 text-xs">{t.plannedStart.toLocaleString("en-IN")}</td><td className="px-5 py-4">{t.vehicle?.name || "Unassigned"}<span className="block text-xs text-muted-foreground">{t.driver?.name || "Unassigned"}</span></td><td className="px-5 py-4">{t.cargoWeight} kg</td><td className="px-5 py-4">₹{t.expectedRevenue.toLocaleString("en-IN")}<span className="block text-xs text-primary">₹{t.estimatedMargin.toLocaleString("en-IN")} margin</span></td><td className="px-5 py-4"><StatusBadge>{t.status}</StatusBadge></td><td className="px-5 py-4">{canManage && t.status === "DRAFT" && <div className="flex gap-3"><form action={dispatchTrip}><input type="hidden" name="id" value={t.id}/><button className="text-xs font-bold text-primary">Dispatch</button></form><details><summary className="cursor-pointer text-xs font-bold text-destructive-foreground">Cancel</summary><form action={cancelTrip} className="mt-2 flex gap-2"><input type="hidden" name="id" value={t.id}/><input name="reason" required placeholder="Reason" className="rounded-full border px-2 text-xs"/><button>Confirm</button></form></details></div>}{canManage && t.status === "DISPATCHED" && <details><summary className="cursor-pointer text-xs font-bold text-primary">Complete trip</summary><form action={completeTrip} className="mt-2 grid w-52 gap-2"><input type="hidden" name="id" value={t.id}/><input name="finalOdometer" type="number" required placeholder="Final odometer" className={fieldClass}/><input name="litres" type="number" step=".01" placeholder="Fuel litres" className={fieldClass}/><input name="fuelCost" type="number" step=".01" placeholder="Fuel cost" className={fieldClass}/><button className={buttonClass}>Complete</button></form></details>}</td></tr>)}</tbody></table></div>
  </div>;
}
